services:
  # --- Relational Database (PostgreSQL) ---
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    ports:
      - "5433:5432" # <--- CAMBIATO: La porta sinistra (Windows) Ã¨ ora 5433
    environment:
      - POSTGRES_USER=mario
      - POSTGRES_PASSWORD=start
      - POSTGRES_DB=ecommerce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- NoSQL Database (MongoDB) ---
  mongo:
    image: mongo:7.0
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

  # --- Caching & Session (Redis) ---
  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

  # --- Event Streaming (Kafka + Zookeeper) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ecommerce-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ecommerce-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # --- Identity Provider (Keycloak) ---
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: ecommerce-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080" # Mappato su 8180 per non collidere con le app Spring
    depends_on:
      - postgres

  # --- Distributed Tracing (Zipkin) ---
  zipkin:
    image: openzipkin/zipkin
    container_name: ecommerce-zipkin
    ports:
      - "9411:9411"

  # --- Email Testing (Mailhog) - Bonus per notifiche ---
  mailhog:
    image: mailhog/mailhog
    container_name: ecommerce-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI

volumes:
  postgres_data:
  mongo_data: