server:
  port: 8081
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ecommerce_db
    username: mario
    password: start
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Crea/Aggiorna le tabelle in automatico
    show-sql: true # Vedremo le query nella console (utile per debug)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect